print("=====Question 1====")
print("'2 > 4'?")
print(2 > 4)
print("====Question 2====")
print("'x >4'?")
x = 8
print(x > 4)
print("====Question 3====")
print("'13 == 13'?")
print(13 == 13)
print("====Question 4====")
print("'x == 12'?")
print(x == 12)
print("====Question 5====")
print("'3.1 == pi'?")
import math
print(3.1 == math.pi)
print("====Question 6====")
print("'2 < 2'?")
print(2 < 2)
print("====Question 7====")
print("'2 <= 2'?")
print(2 <= 2)
print("====Question 8====")
a,b,c = 2,-1,4
print("The discriminant of (2(x*x)-x+4 is negative?")
print(((b**2)-(4*a*c))<0)
print("====Question 9====")
print("'3 < 7' and len([1,1,0,1,0] == 3'?")
print((3 < 7) and len([1,1,0,1,0]) == 3)
print("====Question 10====")
print("'3.14 == pi'?")
print(3.14==math.pi)
print("====Question 11====")
print("Is the name Grace?")
name = "Grace"
print(name.title() == "Grace")
print("====Question 12====")
print("Did the user enter q or Q?")
user_choice = "p"
print(f"user chose {user_choice}")
print(user_choice == "Q" or user_choice == "q")
user_choice = "P"
print(f"user chose {user_choice}")
print(user_choice == "Q" or user_choice == "q")
user_choice = "q"
print(f"user chose {user_choice}")
print(user_choice == "Q" or user_choice == "q")
user_choice = "Q"
print(f"user chose {user_choice}")
print(user_choice == "Q" or user_choice == "q")
print("====Question 13====")
print("'3 < 5 and 5>=3'?")
print(3 < 5 and not (5 < 3))
print("====Question 14====")
print("'(3 < 4 or 5 < 3) and 6 < 3'?")
print(((3 < 4) or (5 < 3)) and (6 < 3))
print("====Question 15====")
print("Is Katie 6 letters long and is 3 less than 5?")
print((len("Katie") == 6) and (3 < 5))
